### ISSUE TITLE
Some JGI slots should be locked/ not edited by user

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/issues#409]
**Deliverable this task is associated with**

_See Deliverables tab here: https://docs.google.com/spreadsheets/d/1z_b6WbuTk4pI0Q-Z-rfCgC-8R3m3F2_JDevYuK8CjYE/edit?usp=sharing_

- 2

**RACI**

_Tag people in their roles_
- Responsible: Montana
- Accountable: Montana
- Consulted:
- Informed:

**Describe the the task?**
- [x] microbiomedata/nmdc-schema#1107
- [x] microbiomedata/issues#434
- [x] [Design process/ how slots will be lock & un-editable](https://github.com/microbiomedata/issues/issues/412)
- [x] microbiomedata/nmdc-schema#1767
- [ ] Design how to add JGI provided information into someones submission (BLOCKED)
- [ ] https://github.com/microbiomedata/issues/issues/410

**Criteria for completion**
- JGI provided metadata slots are locked and uneditable by the submitter.

**Estimate people time**
- 20

**Completion Date (Goal)**
- ~Oct 20~
- Variable due dates for each sub task

**Target Sprint Start & End Dates**
- Start: Sept 11
- End: Oct 20

**Tag Blocker/Contingent upon isues**
- [Tagg issues]

**Comment by mslarae13** [comment]
Brainstorming ways to get the 'locked' information from JGI PMs into the NMDC submission portal

- User uploads a metadata file
^How do we share/ get a file to them?
^ File will need to be re-formatted from JGI PM
^ How do we make sure the sample name the user inputs lines up with the names in the JGI sheet?

- Putting in the JGI UP # will hook into JGI system and pull the information
^JGI PM will have to have input this information somewhere
^ Infrastructure will need developed to allow for this. API?
^ Will and API hook be fast enough?
^ How do we make sure the sample name the user inputs lines up with the names in the JGI sheet?

? Does the user enter it? Or the JGI PM?
? Should the user START with NMDC? Then JGI adds / provides information?

**Comment by mslarae13** [comment]
Part of https://github.com/microbiomedata/issues/issues/444

**Comment by mslarae13** [comment]
See NMDC google doc JGI-NMDC_Current and Proposal_v2.2

The workflow has been agreed upon. 
Need to add / clarify

- [ ] What JGI products will the NMDC submission portal support
- [ ] What are the exact work items
- [ ] What is the status / information needed to pull from JGI API.

**Comment by mslarae13** [comment]
UX and matching JGI provided information blocked unitl API is created

**Comment by mslarae13** [comment]
@pkalita-lbl I think we can close this parent issue. You locked the slots & we have a separate issue for ingesting the metadata from the API.

**Comment by pkalita-lbl** [comment]
Fine by me. Closing.
