### ISSUE TITLE
What additional sample types should be available for EMSL metadata submission via NMDC

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/issues#417]
**Deliverable this task is associated with**

_See Deliverables tab here: https://docs.google.com/spreadsheets/d/1z_b6WbuTk4pI0Q-Z-rfCgC-8R3m3F2_JDevYuK8CjYE/edit?usp=sharing _

- 7

**RACI**

_Tag people in their roles_
- Responsible: @mslarae13 
- Accountable: @mslarae13
- Consulted:
- Informed:

**Describe the the task?**
- [x] Identify additional sample types for NMDC submission for EMSL samples
- [x] microbiomedata/nmdc-schema#1335
- [x] [Add slots / update NMDC submission schema for expanded EMSL samples](https://github.com/microbiomedata/submission-schema/issues/158)
- [x] [remove env package slot & fill in this slot in DB using the package that is checked](https://github.com/microbiomedata/issues/issues/543)
- [x] microbiomedata/submission-schema#183
- [ ] microbiomedata/nmdc-server#1154

**Criteria for completion**
- Additional sample types are available for NMDC metadata submission for EMSL sample submission

**Estimate people time**
- 30

**Completion Date (Goal)**
- 10/6
- Rescheduled 02/09

**Target Sprint Start & End Dates**
- Start: 9/11
- End: 02/09

**Tag Blocker/Contingent upon issues**
- [Tagg issues]

**Comment by mslarae13** [comment]
@brynnz22 , @pkalita-lbl , @bmeluch  please break into / link smaller issues

**Comment by mslarae13** [comment]
Delayed, initial thoughts
plant-associated
sediment
water

**Comment by mslarae13** [comment]
Identification of sample types complete. @bmeluch is working on inventorying /checking slots. Bea, can you create an issue for this work?

**Comment by mslarae13** [comment]
Part of https://github.com/microbiomedata/issues/issues/444

**Comment by mslarae13** [comment]
Decision, skip pore-water... should a user complete soil or water metadata is VERY unclear and records in NCBI are all over the place. This should likely be a MIxS extension first.

**Comment by ssarrafan** [comment]
@mslarae13 is this issue still 'in progress'?  Or should it be moved to backlog?

**Comment by mslarae13** [comment]
@ssarrafan advice on the best way to manage the inprogess of super issues? This is in progress cuz it's the full picture, but the individual broken out work is linked (super issue)

**Comment by ssarrafan** [comment]
> @ssarrafan advice on the best way to manage the inprogess of super issues? This is in progress cuz it's the full picture, but the individual broken out work is linked (super issue)

I think leaving it in the squad board and then adding the related active issues to the current sprint would be great.

**Comment by mslarae13** [comment]
This looks done! Submitting a separate ticket for validating or limiting sample type options. This is a future problem.
https://github.com/microbiomedata/nmdc-server/issues/1185
