### ISSUE TITLE
Study Refresh Squad: submit changesheet and Mcafe umbrella study

### ISSUE THREAD

**Issue by brynnz22** [microbiomedata/issues#570]
- [x] Mint Id for new study  here: https://docs.google.com/spreadsheets/d/1kg_f5fdKj0YjAWD69w7iUIEcKHPUOp_1IVHXjEIwyGM/edit#gid=397435158
- [ ] Add study to data portal using json submit endpoint
- [x] add minted study identifier for the part_of in the red highlighted part of the change sheet here: https://docs.google.com/spreadsheets/d/1Fn_IdYQDrEPlgAdvuNHxL39H7wmeZaag4a_-FBYdVBU/edit#gid=0
- [ ] Update the doi changes in the above change sheet to work for the way DOIs are structured (e.g. a list of dictionaries). See the documentation here: https://microbiomedata.github.io/nmdc-runtime/howto-guides/author-changesheets/
- [ ] Validate changesheet using the validate endpoint
- [ ] submit change sheet once validates

**Comment by brynnz22** [comment]
Alicia minted it and it is `nmdc:sty-11-abkzcd11`

I tried submitting new study, but does not look like it worked. I am looking into it.

**Comment by brynnz22** [comment]
New study is added and changes are submitted. I confirmed they are in mongo. Kitware just needs to do an ingest to show changes on portal.
