### ISSUE TITLE
Gather and report metrics on BER slide

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/issues#706]
#### Tasks

- [x] Confirm (ask) what timeframe the report is about
  - Slide currently says "FY24 Q1" but that may be because it hasn't been updated to something newer yet
- [ ] Gather metrics using procedure documented on Slack (or copy from existing reports if already reported)
- [ ] Work with teammates to gather submission metrics (if I don't already have them for the timeframe in question)
- [ ] Update BER slide

The link to the slide is in an email in my inbox.

Deadline: ???

**Comment by eecavanna** [comment]
- The timeframe the report is about is: FY24 Q2.

**Comment by eecavanna** [comment]
There was nothing to do here. We already had the data in a different presentation.
