### ISSUE TITLE
Feedback on submission portal updates Feb 2023

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#73]
**Get into Production by March 8th**
- [x] microbiomedata/nmdc-server#865
- [x] microbiomedata/nmdc-server#866
- [x] microbiomedata/nmdc-server#867
- [x] microbiomedata/nmdc-server#868
- [x] microbiomedata/nmdc-server#869
- [x] microbiomedata/nmdc-server#870
- [x] microbiomedata/nmdc-server#871
- [x] microbiomedata/nmdc-server#872
- [x] microbiomedata/issues#87
- [x] microbiomedata/issues#88

**Complete by GSP**
- [x] microbiomedata/issues#101
- [x] microbiomedata/issues#102
- [x] microbiomedata/issues#103
- [x] microbiomedata/issues#99
- [x] microbiomedata/issues#104
- [x] microbiomedata/issues#105
- [x] microbiomedata/nmdc-server#878
- [x] microbiomedata/issues#107
- [x] microbiomedata/nmdc-server#879
- [x] #110
- [x] microbiomedata/nmdc-server#880
- [x] #111
- [x] #112
- [x] #113
- [x] #116
- [x] #117
- [x] #119
- [x] #129
- [ ] Typo in alternate names
- [x] #128

**After GSP** 
- [ ] Study Information: Autopopulate your information in PI or contributor role
- [ ] Multiomics: Enable JGI metaB
- [ ] Study Information: Remove EMSL and JGI check boxes if "data will NOT be generated at a UF"
- [ ] #118
- [ ] Metadata: Example row in the template
- [ ] Metadata: Make JGI pre-provided fields a different color
- [ ] microbiomedata/issues#98
- [ ] Shipping info: EMSL experiment goals 
- [ ] Add a pop up that says metadata valid and complete
- [ ] #122
- [ ] #114 moving from GSP list 4/7/23
- [ ] #115 moving from GSP list 4/7/23

I'll create a new issue for the AFTER GSP items in the [Post GSP Board](https://github.com/orgs/microbiomedata/projects/54/views/1)

**Comment by ssarrafan** [comment]
@mslarae13 do you need this GH issue to track the feedback or do you have another issue already opened?  
Moving to the next sprint as feedback is still coming in.

**Comment by mslarae13** [comment]
@naglepuff 
Looks like these 1st collection of issues are ready for testing in dev

**Comment by naglepuff** [comment]
Yes, those changes should all be in dev.

**Comment by mslarae13** [comment]
Tested the March updates. Looks great!!! Good to push to production!

**Comment by mslarae13** [comment]
This will not be in the next sprint as mike will be working on the data portal & submit button for the submission portal next. But might come back end of March.

**Comment by ssarrafan** [comment]
@mslarae13 you'll be pleasantly surprised that a lot of the fixed were done this sprint. Moving this issue to the next sprint to continue with the remaining items. Big thanks to @pkalita-lbl and @naglepuff

**Comment by ssarrafan** [comment]
Closing this. Opened a[ new issue](https://github.com/microbiomedata/issues/issues/203) for post GSP items.
