### ISSUE TITLE
Make spreadsheet of GitHub labels that exist in all `microbiomedata` repositories

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/issues#753]
#### Background

Some team members (including me) want to standardize labels (to some extent) across repos. We think having a list of existing labels will help us do that.

#### Task

- [x] Write script that builds a spreadsheet of all labels that exist in all `microbiomedata` repos
      - Include their descriptions
      - If easy, include info about how many times a given label is used
      - If easy, include some "diffs" between repos' labels
- [x] Run the script and provide the resulting spreadsheet to team members*
      - \* @mslarae13 is interested in seeing such a spreadsheet

**Comment by eecavanna** [comment]
This is done. I added the results to a spreadsheet created by @ssarrafan and shared with @mslarae13.

**Comment by eecavanna** [comment]
Re-opening. 

Additional task:
- [ ] Share Jupyter notebook with teammates so they can re-generate the same spreadsheets later (even in other orgs)

**Comment by eecavanna** [comment]
Re-closing. I opened a PR in the issues repository ([here](https://github.com/microbiomedata/issues/pull/758)) where I propose adding the Jupyter notebook to that repository.
