### ISSUE TITLE
Berkeley Schema Roll Out: "Flip the switch" in production (meta issue)

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/issues#823]
This Issue contains team members' plans for the day when we switch the production environment from using the "Legacy schema" to using the "Berkeley schema."

### FAQ

1. **How can I add a task to this list?** Edit this Issue description directly. Please save your edits often to avoid content conflicts.
2. **Is the flowchart always in sync with the task list?** No, someone sporadically updates it to match the task list. The task list is the authoritative list and the flowchart is supplementary.
3. **This seems error prone to me.** Me, too. I'll propose we draft this in a Google Doc and then put the resulting plan here in a GitHub Issue.

### Prerequisite tasks

This is stuff that will be done before "flip the switch" day.

- [ ] **Announce eventual downtime**: Announce eventual downtime event in `#general` channel on Slack
- [ ] **Merge Runtime's berkeley branch into main**: Merge `nmdc-runtime/berkeley` into `nmdc-runtime/main` (@eecavanna)
  - This depends upon `berkeley-schema-fy24/main` already having been merged into `nmdc-schema/main` and the resulting schema being accessible on PyPI (as `nmdc-schema` version 11).

### Tasks

This is stuff that will happen on "flip the switch" day.

- [ ] **1. Announce impending downtime**: Announce impending downtime event in `#general` channel on Slack
- [ ] **2. Take production Runtime offline**: Scale down the production Runtime, Dagster, Scheduler, and Aggregator workloads on Spin to 0 replicas (@eecavanna)
- [ ] **3. Migrate production Mongo database**: Run Berkeley migration notebook (currently in a PR) to migrate the production Mongo database from conforming to the legacy schema to conforming to the Berkeley schema. Note: The notebook will handle revoking/restoring user access. (@eecavanna)
- [ ] **4. Update production Runtime**: Create a GitHub Release of `nmdc-runtime/main`, which will update the production Runtime and Dagster versions on Spin. (@eecavanna)
- [ ] **5. [...]**

### Flowchart

```mermaid
flowchart TB
    1["Announce impending downtime"]
    --> 2["Take production Runtime offline"]
    --> 3["Migrate production Mongo database"]
    --> 4["Update production Runtime"]
    --> 5["..."]
```

**Comment by mslarae13** [comment]
@eecavanna is this the issue you started then switched to google doc for initial planning?

**Comment by eecavanna** [comment]
Yes, this is that one.

**Comment by eecavanna** [comment]
Closing in favor of https://github.com/microbiomedata/issues/issues/873
