### ISSUE TITLE
Super Issue: Eliminate Sandbox Environment

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/issues#825]
This is a meta issue.

Here are all the tasks necessary to allow us to eliminate the Submission Portal sandbox environment without sacrificing the benefits that that environment was providing to us.

Feel free to update each of these bulleted issues to combine or separate tasks as needed.

### Tasks

- [x] #826
  - Anyone with “creator role” (submitter & PIs) and admins can delete a submission
- [x] #827
  - "Test", "fake", "workshop", "experimental", "temporary", idk what the right word is...
  - Provide clear tooltip text to elaborate / explain when to make a real submission vs a test submission
- [x] #828
- [ ] https://github.com/microbiomedata/nmdc-field-notes/issues/153
- [x] Add ability to track what submissions in the submission portal come from the app (for metrics)
- [x] https://github.com/microbiomedata/nmdc-server/issues/1549
- [x] https://github.com/microbiomedata/nmdc-server/issues/1285
- [x] #829
- [x] #830
 
### Notes

- No deletion policy for test submissions until we get a good sense of HOW test submissions are being created & IF people delete their own tests
 
### Eliminate sandbox environment

- AFTER submission portal updates has been done, tested, and rolled out, delete sandbox env

**Comment by mslarae13** [comment]
@eecavanna would you mind making the issues for the field notes app?

**Comment by eecavanna** [comment]
Hi @mslarae13, I created an issue for the Field Notes app and added it to the list above.

**Comment by mslarae13** [comment]
@eecavanna can you add any infrastruture items we need to also check in on? 
To actually eliminate this environment.

**Comment by eecavanna** [comment]
Regarding infrastructure, here are the 6 services (containers) that make up the "sandbox" environment. All of these are part of the Data Portal stack (as opposed to the Runtime stack). As part of eliminating the environment, we'd delete all of these things—as well as the other Kubernetes resources that they use (e.g. volumes, ingresses, the CronJob that clears submissions, etc.).

<img width="712" alt="image" src="https://github.com/user-attachments/assets/3635e517-9b0c-47d9-adf3-c7a7f8620738">

In addition, there is also 1 DNS record on Cloudflare that is specific to the "sandbox" environment. As part of eliminating the environment, we would also delete this DNS record (not urgent).

<img width="1149" alt="image" src="https://github.com/user-attachments/assets/15fe7888-98b7-41fe-a1db-bb51d2616de4">

Finally, there is a DNS record on LBLnet that is specific to the "sandbox" environment. This is another thing we'd delete as part of eliminating the environment.

<img width="1380" alt="image" src="https://github.com/user-attachments/assets/1efa53bf-6c03-43ac-9fd7-dbcf71544eef">

**Comment by eecavanna** [comment]
I deleted the sandbox environment this afternoon. Details (optional reading) are in [this GitHub comment](https://github.com/microbiomedata/infra-admin/issues/185#issuecomment-2787455325).
