### ISSUE TITLE
Add banner announcing Oct 15-16 maintenance (Runtime, Data Portal, and Status website)

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/issues#902]
Task
- [x] microbiomedata/nmdc-runtime#726
- [x] microbiomedata/nmdc-server#1412
- [x] microbiomedata/nmdc-status-website#10

**Comment by eecavanna** [comment]
Done in 2/3 places. PR for 3rd place is awaiting review.

**Comment by eecavanna** [comment]
This is done. Thanks, @pkalita-lbl, for taking care of the Git and deployment aspects of the Data Portal one (after I accidentally implemented the banner on a branch in a way that was not compatible with our standard hotfix process).
