### ISSUE TITLE
Release 2024.11

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#914]
Deployment to production will be: **Tuesday, November 19**.

New `nmdc-schema` and `submission-schema` versions should be ready and released and integrated into dev systems by **Tuesday, November 12**.

**Comment by aclum** [comment]
workflow_execution_set should be run through linkml-validate against the 11.1.* version of the schema to confirm that changes in https://github.com/microbiomedata/nmdc-schema/pull/2225 does not make any existing mongo data invalid.

**Comment by eecavanna** [comment]
This release will include a migration.

**Comment by aclum** [comment]
This release needs to be coordinated with updating the image for the aggregation deployment in SPIN to [v2.1.0](https://github.com/microbiomedata/nmdc-aggregator/releases/tag/v2.1.0), image is in ghcr.

**Comment by eecavanna** [comment]
Thanks for the heads up, @aclum, and for getting the container image onto GHCR already (I see it there).

Do you want that container image to be deployed to the development environment already? The development environment is currently running container image version `0.10.2`, as shown below.

<img width="625" alt="image" src="https://github.com/user-attachments/assets/047bdcb9-e137-4e97-b8ad-c07f346cb3ea">

**Comment by aclum** [comment]
I have permissions on rancher2 now so I just updated the aggregation @eecavanna in nmdc-dev. @naglepuff you should be able to test your nmdc-server changes in https://github.com/microbiomedata/nmdc-server/pull/1433 against dev now.

**Comment by pkalita-lbl** [comment]
This is mostly an FYI, but it's also something I'd like to verify post release. 

In https://github.com/microbiomedata/nmdc-server/pull/1445 I updated the nginx configuration in the image that the `portal-frontend` workloads use. The goal was to allow a user to save their submission when the sample metadata size grew larger than 1 MB. The changes use the [client_max_body_size](https://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size) directive in the nginx config, and the particular value used can come from an environment variable (or 10 MB if not set).

However when I went to test those changes on dev I saw that the `PATCH` requests with the large payload size were still being rejected. I realized that the Rancher ingress has _it's own_ payload size setting (default 1 MB). So I added the following annotation to the `data-dev` ingress:

```yaml
nginx.ingress.kubernetes.io/proxy-body-size: 100m
```

Visually, it's now like this on dev:
```mermaid
flowchart LR
    A[User]-->B["Rancher Ingress<br/>(max payload 100 MB, set by ingress config)"]
    B-->C["nginx<br/>(max payload 10 MB, set by environment variable)"]
    subgraph portal-frontend
    C-->D[fastapi]
    end
```

I feel okay about leaving the ingress' size relatively high, since there is a second size checkpoint right after it. 

To that end **I've already set `nginx.ingress.kubernetes.io/proxy-body-size` on the (prod) `data` ingress as well**. But I'd still like to specifically test that once the release is out.

**Comment by eecavanna** [comment]
Thanks, @pkalita-lbl.

FYI: There is one more box between "User" and "Rancher Ingress," which is Cloudflare. LBL IT recently increased our max request size (for all `microbiomedata.org` domains) to 5 GB (to enable some functionality of the NMDC EDGE instance that was — at the time — being served at a `microbiomedata.org` domain), so Cloudflare will not be the gating factor here.

**Comment by eecavanna** [comment]
This release is currently blocked by https://github.com/microbiomedata/nmdc-server/issues/1449.

For future reference, I'm, personally, comfortable with postponing this release (e.g. to later in the week).

**Comment by aclum** [comment]
Blocked on https://github.com/microbiomedata/nmdc-server/issues/1450

**Comment by eecavanna** [comment]
A follow-on task for the release:
- [ ] Run [refscan](https://github.com/microbiomedata/refscan) against the production database. I expect this to take less than 5 minutes.

**Comment by aclum** [comment]
reorganizing blockers so it is easier to see what is resolved vs outstanding
potential blockers:
 - [ ] https://github.com/microbiomedata/nmdc-server/issues/1449 - confirmed resolved in dev
 - [ ] https://github.com/microbiomedata/nmdc-server/issues/1450 - tested locally, dev TBD
 - [ ] https://github.com/microbiomedata/nmdc-server/issues/1451 - tested locally, dev TBD

**Comment by eecavanna** [comment]
I missed the Release Planning meeting on November 4. I had volunteered to drive this release. **I am planning to drive it.**

I don't know whether anyone has volunteered to copilot it. Having no copilot is OK with me (having gone through the process a few times at this point), although I would prefer to have one.

**Comment by eecavanna** [comment]
> workflow_execution_set should be run through linkml-validate against the 11.1.* version of the schema to confirm that changes in [microbiomedata/nmdc-schema#2225](https://github.com/microbiomedata/nmdc-schema/pull/2225) does not make any existing mongo data invalid.

This will be accomplished during the second half of the migration process, taking place today (as part of today's release). After transforming the documents in the Mongo collections (in a local transformation Mongo server), those Mongo collections will be validated (using LinkML's `Validator` class) against the `11.1.0` version of the schema.

**Comment by eecavanna** [comment]
Hi @aclum, I have a question about this "extra task":

> This release needs to be coordinated with updating the image for the aggregation deployment in SPIN to [v2.1.0](https://github.com/microbiomedata/nmdc-aggregator/releases/tag/v2.1.0), image is in ghcr.

The aggregator in the production environment is currently at version 2.0.0, as shown here:

![image](https://github.com/user-attachments/assets/7daa3deb-282c-49d2-9cfd-c05fe41360df)

At what point do you want it to be updated to be at version 2.1.0; for example, after doing all the other steps of the release process, but before announcing the release is complete?

**Comment by aclum** [comment]
Anytime after the mong prod migration but before announcing the release is complete.

**Comment by eecavanna** [comment]
The aggregator in the production environment was updated at about 1:50pm PT today.

![image](https://github.com/user-attachments/assets/b30c84e3-b301-4a71-972c-55b9062133f0)

**Comment by eecavanna** [comment]
Ingest finished just now. Closing since the release is now done. Big thanks to @pkalita-lbl for stepping in and taking the wheel as I stepped out for a meeting early in the release process.
